---
title: "Notebook Week 1"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

Just a couple of simple implementations to get our hands dirty.

## Define Parameters

```{r}
endTime = 10

parameters <- c(
  beta = 0.7,
  gamma = 0.1,
  N = 60
)

initial <- c(
  S = 59,
  I = 1
)
```

## Deterministic Model

(using the logarithmic form recommended by Felicia)

```{r}
library(deSolve)

state <- c(
  X = log(initial[["S"]]),
  Y = log(initial[["I"]])
)

Infection <- function(t, state, parameters) {
  with(as.list(c(state, parameters)),{
    dX <- -beta * exp(Y) / N
    dY <- beta * exp(X) / N - gamma
    list(c(dX, dY))
  })
}

times <- seq(0, endTime, by=0.01)
out <- ode(y=state, times=times, func=Infection, parms=parameters)
png()
par(mfrow=c(1,2), mar=c(5,4,0,0), oma=c(1,0,3,0))
plot(out[, "time"], lapply(out[, "Y"], exp), xlab="t", ylab="I")
plot(out[, "time"], lapply(out[, "X"], exp), xlab="t", ylab="S")
```

## Stochastic Model

```{r}
times <- c(
  0
)

current_time <-  0
next_T <-  0

beta = parameters[["beta"]]
gamma = parameters[["gamma"]]
N = parameters[["N"]]

S <-  c(initial[["S"]])
I <-  c(initial[["I"]])
R <-  c(0)

# for loop
while (current_time < endTime){
    latest_S <- tail(S,1)[1]
    latest_I <- tail(I,1)[1]
    latest_R <- tail(R,1)[1]
    next_T <- rexp(1, beta * latest_S * latest_I / N + gamma * latest_I)
    U <- runif(1)
    if (U < (beta * latest_S / N) / (beta * latest_S / N + gamma)) {
      S <- c(S, latest_S - 1)
      I <- c(I,latest_I + 1)
      R <- c(R, latest_R)
    }
    else {
      S <- c(S, latest_S)
      I <- c(I,latest_I - 1)
      R <- c(R, latest_R + 1)
    }
    times <- c(times,current_time + next_T)
    current_time = tail(times, 1)[1]
}
print(times)
print(I)

combined <- list(times = times, I = I)
print(combined)
df = as.data.frame(do.call(cbind, combined))
print(df)

png()
ggplot(df, aes(x = times, y = I)) +
          geom_point()

```
