## R notebook to compare and plot the Markov Chain probability distribution, vs a sample after running the experiment.

### Load libraries and set parameters

```{r}
library(ggplot2)
library(Matrix)
knitr::opts_chunk$set(echo = TRUE)
source('MarkhovChain.R')
source('Experiment.R')

t <-  30
Beta <- 0.8
Gamma <- 0.44
N <- 60
```

### Generate overlapping graph

```{r}
mass_matrix = markhov_probability(times=t, beta=Beta, gamma=Gamma, initial_S=N-1, initial_I=1, immunity=FALSE)
exp_df = experiment(1000, t, N, Beta, Gamma, N-1, 1, SIS=TRUE)
# print(as.vector(exp_df[["probs"]]))
df = data.frame(I=as.integer(colnames(mass_matrix)), P=as.vector(mass_matrix), E=as.vector(exp_df[["probs"]]))
# print(df["E"])
ggplot(data = df, aes(x = I)) + 
  geom_col(aes(y=P),color="aliceblue", fill=alpha("blue1",0.7)) + 
  geom_col(aes(y=E),color="seashell", fill=alpha("red1", 0.4)) +
  ylab('P(I)') +
  theme_classic() +
  theme(plot.title=element_text(family="sans", hjust = 0.5)) +
  ggtitle("PMF for Infection")
# data.frame(markov_virus(end_time=60,beta=0.88, gamma=0.4, S=59, I=1))
```
